### ISSUE TITLE
Connect failed:  database "Petter" does not exist

### ISSUE THREAD

**Issue by petterannerwall** [dbgate/dbgate#167]
**Describe the bug**
Cannot connect to Amazon Redshift database since I cannot enter any database name. DbGate seems to use my windows user as the default database name. Tried searching and found issue https://github.com/dbgate/dbgate/issues/96 and fix https://github.com/dbgate/dbgate/issues/92 which says that this should be possible. 

**To Reproduce**
Fill in connection info and try to connect to the database

**Expected behavior**
Expected to be able to specify database name instead of taking the logged-in user's name as the database name.

**Screenshots**
![image](https://user-images.githubusercontent.com/5909669/133572641-3c479082-3405-44b5-9cbf-857cb7292180.png)

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version 4.2.8
 - Install source Installer from here https://dbgate.org/download/
 - Type - Web/Application
 - Database engine: Amazon Redshift

**Additional context**
This maybe?

```
error: database "Petter" does not exist
    at c.parseE (C:\Users\Petter\AppData\Local\Programs\dbgate\resources\app.asar\packages\plugins\dbgate-plugin-postgres\dist\backend.js:9:126259)
    at c.parseMessage (C:\Users\Petter\AppData\Local\Programs\dbgate\resources\app.asar\packages\plugins\dbgate-plugin-postgres\dist\backend.js:9:123386)
    at Socket.<anonymous> (C:\Users\Petter\AppData\Local\Programs\dbgate\resources\app.asar\packages\plugins\dbgate-plugin-postgres\dist\backend.js:9:119630)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

Error JSON: {
  "name": "error",
  "length": 136,
  "severity": "FATAL",
  "code": "3D000",
  "file": "/home/ec2-user/padb/src/pg/src/backend/utils/init/postinit.c",
  "line": "517",
  "routine": "LcInitPostgres"
}

Connection: {
  "engine": "redshift@dbgate-plugin-postgres",
  "sshMode": "userPassword",
  "sshPort": "***",
  "sshKeyfile": "***",
  "databaseUrl": "***",
  "user": "***",
  "password": "***",
  "displayName": "***",
  "useSsl": false,
  "_id": "***",
  "status": "***"
}

Platform: win32
```

**Comment by janproch** [comment]
Database URL should contain database name, add /DBNAME to the end of database URL, where DBNAME is your database name. When you use button "Copy database URL" (or something similar) in AWS redshift console, it should copy URL already with database name

**Comment by petterannerwall** [comment]
Thanks that worked! I never looked in the amazon redshift console, just took the connection string from another application.
