### ISSUE TITLE
sshtunnel proxy error

### ISSUE THREAD

**Issue by spiritwindy** [dbgate/dbgate#179]
system:window7
election:12.18.3
drive:mysql
error: linux ssh proxy crash, end of process api 
suggest:use election 15

**Comment by janproch** [comment]
Thank you for the report.

Could you please run DbGate from console and add console output here?

**Comment by spiritwindy** [comment]
Creating SSH tunnel to 120.24.169.61-127.0.0.1:3306, using local port 10000 (node:9892) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc (), Buffer.allocUnsafe(), or Buffer.from() methods instead. [1012/103835.461:ERROR:crashpad_client_win.cc(808)] not connected

**Comment by spiritwindy** [comment]
09:47:49.717 > Error: Error: net::ERR_CONNECTION_RESET
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6497)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.callbackTrampoline (internal/async_hooks.js:120:14)
Error: net::ERR_CONNECTION_RESET
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6497)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.callbackTrampoline (internal/async_hooks.js:120:14)

**Comment by janproch** [comment]
Please add full console output if possible. I can' see context of this message.
