### ISSUE TITLE
BUG: missing cluster name in connection string on CockroachDB Cloud

### ISSUE THREAD

**Issue by ibmendoza** [dbgate/dbgate#191]
**Describe the bug**
This error message appears while using CockroachDB (CockroachCloud Serverless) even though the connection was successful (Connected:  CockroachDB CCL v21.2.0-beta.4-20-g3061813685 (x86_64-unknown-linux-gnu, built 2021/10/15 07:02:45, go1.16.6)

**codeParamsRoutingFailed: missing cluster name in connection string**

Additional error details:

error: codeParamsRoutingFailed: missing cluster name in connection string
    at c.parseE (/tmp/.mount_dbgateSaYqu9/resources/app.asar/packages/plugins/dbgate-plugin-postgres/dist/backend.js:9:152510)
    at c.parseMessage (/tmp/.mount_dbgateSaYqu9/resources/app.asar/packages/plugins/dbgate-plugin-postgres/dist/backend.js:9:149637)
    at TLSSocket.<anonymous> (/tmp/.mount_dbgateSaYqu9/resources/app.asar/packages/plugins/dbgate-plugin-postgres/dist/backend.js:9:145881)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)

Error JSON: {
  "name": "error",
  "length": 87,
  "severity": "FATAL",
  "code": "08004"
}

Connection: {
  "server": "***",
  "engine": "cockroach@dbgate-plugin-postgres",
  "sshMode": "userPassword",
  "sshPort": "***",
  "sshKeyfile": "***",
  "user": "***",
  "password": "***",
  "useSsl": true,
  "sslCaFile": "***",
  "_id": "***",
  "status": "***",
  "useSshTunnel": false,
  "displayName": "***"
}

Platform: linux

<br class="Apple-interchange-newline">

**To Reproduce**
1. Add Connection > Main and SSL tabs
2. Click on Test and Save buttons
3. See error

**Expected behavior**
Should not display error message

**Version Information (please complete the following information):**
 - OS: Linux Mint 20.2 Cinnamon
 - App Version: Version: 4.3.4, Build date: 2021-10-31
 - Install source: AppImage
 - Database engine: CockroachDB Cloud

If there is a **connection string** option. this would solve the problem.

**Comment by janproch** [comment]
Thanks for feedback. I added posibility to use custom connection string, when connecting to PostgreSQL or CockroachDB. Released in 4.4.0
