### ISSUE TITLE
QUESTION: Where can I define "encrypt" option for MSSQL connection to Azure?

### ISSUE THREAD

**Issue by michalszajnecki** [dbgate/dbgate#195]
Where can I define "encrypt" option for MSSQL connection to Azure? Right now, connection UI is missing that option.

**Details:**

Connection error
```
ConnectionError: Server requires encryption, set 'encrypt' config option to true.
    at i (/opt/dbgate/resources/app.asar/packages/plugins/dbgate-plugin-mssql/dist/backend.js:23:77403)
    at L.message (/opt/dbgate/resources/app.asar/packages/plugins/dbgate-plugin-mssql/dist/backend.js:437:207486)
    at L.dispatchEvent (/opt/dbgate/resources/app.asar/packages/plugins/dbgate-plugin-mssql/dist/backend.js:437:193931)
    at f.<anonymous> (/opt/dbgate/resources/app.asar/packages/plugins/dbgate-plugin-mssql/dist/backend.js:437:191436)
    at f.emit (events.js:315:20)
    at i.<anonymous> (/opt/dbgate/resources/app.asar/packages/plugins/dbgate-plugin-mssql/dist/backend.js:552:307837)
    at i.emit (events.js:327:22)
    at M (/opt/dbgate/resources/app.asar/packages/plugins/dbgate-plugin-mssql/dist/backend.js:159:136133)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Error JSON: {
  "message": "Server requires encryption, set 'encrypt' config option to true.",
  "code": "EENCRYPT"
}

Connection: {
  "server": "***",
  "engine": "mssql@dbgate-plugin-mssql",
  "user": "***",
  "password": "***",
  "defaultDatabase": "***",
  "singleDatabase": true,
  "displayName": "***",
  "_id": "***",
  "options": "***",
  "sshMode": "userPassword",
  "sshPort": "***",
  "sshKeyfile": "***"
}

Platform: Linux
```

and my options are `"options":{"encrypt":true,"trustServerCertificate":false}`

**Version Information**
Operating System: Ubuntu 21.10
App Version [help -> about]: Version: 4.4.0 Build date: 2021-11-15

**Comment by janproch** [comment]
I guess you have not checked Use SSL checkbox on checkbox tab. it should fix this problem

Please let me knot whether this works

![image](https://user-images.githubusercontent.com/2543891/142720373-820bee4a-fd3e-4832-8c16-bb03df894611.png)

**Comment by michalszajnecki** [comment]
it fixed my issue, but I think that message
`Server requires encryption, set 'encrypt' config option to true`
is misleading because what fixed my problem is that checkbox or change in config json
`"useSsl": true`
