### ISSUE TITLE
Problem export data MongoDB to Excel

### ISSUE THREAD

**Issue by maverick-om** [dbgate/dbgate#240]
**Describe the bug**
In the version dbgate v 4.6 allow export data mongodb to MSExcel but en v.4.7 not export.

**To Reproduce**
I select option Export / MS Excel but not data exported and does not generate file xlxs

![image](https://user-images.githubusercontent.com/55114342/156021490-1a849433-e4ab-4854-b7b8-49fea511f625.png)

And when select option Export show the message:
TypeError: Cannot read property 'map' of undefined
at o._write(/snap/dbgate/218/resources/app.asar/package/plugins/dbgate-plugin-excel/dist/backend.js:9:72828)
at writeOrBuffer(internal/streams/writeable.js:358:12)
at o.Writable.write(internal/streams/writeable.js:303:10)
at ondata (internal/streams/readable.js:719:22)
at o.emit(events.js:315:20)
at addChunk (internal/streams/readable.js:309:12)
at readableAddChunk (internal/streams/readable.js:284:9)
at o.Readable.push (internal/streams/readable.js:223:10)
at o.Transform.push (internal/streams/transform.js:166:32)
at o_transform (/snap/dbgate/218/resources/app.asar/package/api/dist/bundle.js:79:56811)

![image](https://user-images.githubusercontent.com/55114342/156021657-bf1b4a26-7374-4519-b6c2-c4505314ecd8.png)

![image](https://user-images.githubusercontent.com/55114342/156021689-80def862-5d29-4c3e-aa60-e5a79522375c.png)

![image](https://user-images.githubusercontent.com/55114342/156021713-ccd146b2-0615-4756-a84b-8b74eee7da40.png)

**Comment by janproch** [comment]
Fixed in 4.7.1

Thanks for reporting
