### ISSUE TITLE
BUG: Connect failed:  connect ECONNREFUSED 127.0.0.1:3306

### ISSUE THREAD

**Issue by Zerotask** [dbgate/dbgate#271]
**Describe the bug**
On my Debian 11 is MariaDB 10.6 installed and I use it for several projects and can connect locally without any problems.

Now I installed the latest DbGate via deb package and accessed it in the browser http://<ip-address>:3000/

I try to connect with Server 127.0.0.1 / localhost, port 3306 and the credentials I use for my other projects, but it always says:
> Connect failed:  connect ECONNREFUSED 127.0.0.1:3306

> Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
Error JSON: {
  "errno": -111,
  "code": "ECONNREFUSED",
  "syscall": "connect",
  "address": "127.0.0.1",
  "port": 3306,
  "fatal": true
}
Connection: {
  "server": "***",
  "engine": "mariadb@dbgate-plugin-mysql",
  "sshMode": "userPassword",
  "sshPort": "***",
  "sshKeyfile": "***",
  "port": "3306",
  "user": "***",
  "password": "***",
  "_id": "***",
  "status": "***"
}
Platform: linux

I don't use SSH Tunnel nor SSL. I also tried the MySQL database engine.
I checked the entered credentials multiple time. I'm also able to connect locally via mysql cli.

**Expected behavior**
A successful connection

**Screenshots**

**Version Information (please complete the following information):**
 - OS: Debian 11
 - App Version: 4.8.6
 - Install source: Deb package (homepage9
 - Type: web
 - Database engine: MariaDB 10.6

**Comment by janproch** [comment]
I am a bit confused. You wrote, that you access dbgate on http://localhost:3000, but debian distribution of dbgate doesn't start web server, it is only classical electron app. So do you use dbgate web app or classical app?

Also it is strange, that in error logs is missing server, user and password (there should be *** placeholder, empty string points to incorrectly saved connection)

One additional question, this error is from connection dialog, test button?

Thanks

**Comment by janproch** [comment]
Do you use dbgate docker image?

If so, localhost address will not work, because it is addressed inside the docker container. 

You could use some of methods for accessing host port described here: https://dev.to/bufferings/access-host-from-a-docker-container-4099

Or use dbgate app or [dbgate-serve](https://www.npmjs.com/package/dbgate-serve) npm package, if you need web version

**Comment by Zerotask** [comment]
At the moment I'm not using the docker image.

I installed it as follow (Opened the website -> Other downloads):
> wget https://github.com/dbgate/dbgate/releases/latest/download/dbgate-latest.deb
> dpkg -i dbgate-latest.deb

Thanks for the blog article and the mentioning of the npm package. I'll look into it.

**Comment by janproch** [comment]
Thanks for testing NPM.

There is still some strangeness in this. You wrote about using localhost:3000, but application installed from debian package does not run as web server, it is only electron app, so localhost:3000 should not work after installing debian package.

However, NPM package should run as web server. But if you had something on port 3000 before, NPM version will start on different port, could you please verify the NPM package port?

**Comment by Zerotask** [comment]
> There is still some strangeness in this. You wrote about using localhost:3000, but application installed from debian package does not run as web server, it is only electron app, so localhost:3000 should not work after installing debian package.

But I actually saw the normal UI with the deb package.

> However, NPM package should run as web server. But if you had something on port 3000 before, NPM version will start on different port, could you please verify the NPM package port?

I tried it 2 times and it always started on a different port and I could open it and saw the DbGate UI. So DbGate in general was working and accessible. It's just always this (probably same) connection error.

You usually get such errors if you try to access a db server from outside localhost which has set in its config not "0.0.0.0" but just "localhost" or "127.0.0.1".

**Comment by janproch** [comment]
Now I noticed, you mentioned about using dbgate docker container in past, are you sure, that you don't have older dbgate instance running in docker on port 3000? ( ```docker ps | grep 3000```  will confirm this)

If no, could you please test this simple node script and copy here a result? Similar code is used in dbgate.

```js
const mysql2 = require("mysql2");

const connection = mysql2.createConnection({
  host: "127.0.0.1",
  port: 3306,
  user: "root",
  password: "YOUR_PASSWORD",
});

connection.query("SHOW DATABASES", (err, res) => {
  console.log("ERROR", err);
  console.log("RESULT", res);
});
```

The config 0.0.0.0 which you mentioned must be configured in mariaDb server, or not?

Thanks for cooperation

**Comment by Zerotask** [comment]
The docker container was actually running. After I stopped it, the npm package dbgate-server started on port 3000.
But the error is still the same:
> Loading module dbgate-plugin-mysql from /home/shopware/.nvm/versions/node/v16.14.2/lib/node_modules/dbgate-serve/node_modules/dbgate-plugin-mysql/dist/backend.js
Loading module dbgate-plugin-mysql from /home/shopware/.nvm/versions/node/v16.14.2/lib/node_modules/dbgate-serve/node_modules/dbgate-plugin-mysql/dist/backend.js
Error: Host '127.0.0.1' is not allowed to connect to this MariaDB server
    at h.asError (/home/shopware/.nvm/versions/node/v16.14.2/lib/node_modules/dbgate-serve/node_modules/dbgate-plugin-mysql/dist/backend.js:1:9129)
    at c.execute (/home/shopware/.nvm/versions/node/v16.14.2/lib/node_modules/dbgate-serve/node_modules/dbgate-plugin-mysql/dist/backend.js:1:16605)
    at p.handlePacket (/home/shopware/.nvm/versions/node/v16.14.2/lib/node_modules/dbgate-serve/node_modules/dbgate-plugin-mysql/dist/backend.js:9:131517)
    at o.onPacket (/home/shopware/.nvm/versions/node/v16.14.2/lib/node_modules/dbgate-serve/node_modules/dbgate-plugin-mysql/dist/backend.js:9:126226)
    at o.executeStart (/home/shopware/.nvm/versions/node/v16.14.2/lib/node_modules/dbgate-serve/node_modules/dbgate-plugin-mysql/dist/backend.js:9:190914)
    at Socket.<anonymous> (/home/shopware/.nvm/versions/node/v16.14.2/lib/node_modules/dbgate-serve/node_modules/dbgate-plugin-mysql/dist/backend.js:9:126372)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10) {
  code: 'ER_HOST_NOT_PRIVILEGED',
  errno: 1130,
  sqlState: '',
  sqlMessage: "Host '127.0.0.1' is not allowed to connect to this MariaDB server"

I also tried to run your snipped and get the same error:
> /var/www/html/dbgate$ node test.js
ERROR Error: Host '127.0.0.1' is not allowed to connect to this MariaDB server
    at Packet.asError (/var/www/html/dbgate/node_modules/mysql2/lib/packets/packet.js:728:17)
    at ClientHandshake.execute (/var/www/html/dbgate/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/var/www/html/dbgate/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/var/www/html/dbgate/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/var/www/html/dbgate/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/var/www/html/dbgate/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10) {
  code: 'ER_HOST_NOT_PRIVILEGED',
  errno: 1130,
  sqlState: '',
  sqlMessage: "Host '127.0.0.1' is not allowed to connect to this MariaDB server",
  sql: undefined
}
RESULT undefined

**Comment by janproch** [comment]
I have found this: https://serverfault.com/questions/900997/mariadb-host-127-0-0-1-not-privileged#:~:text=By%20default%2C%20the%20MySQL%2FMariaDB,host%20that's%20allowed%20to%20connect.

Maybe problem is skip-name-resolve setting in MariaDB server configuration

Also, when you try to connection to "localhost" instead of "127.0.0.1", has it the same problem?

You wrote, that you connect this server locally with no problems, which drivers/software are you using for connecting?

Thanks

**Comment by janproch** [comment]
I have network name "dockerhost" (released now). It could be used in docker distribution, it is host, where docker containers are running.
