### ISSUE TITLE
BUG: cannot specify connection property sslmode=require  

### ISSUE THREAD

**Issue by dataspun** [dbgate/dbgate#314]
**Describe the bug**
Creating/testing a connection fails when attempting to specify sslmode=require

**To Reproduce**
1. Create a connection to PostgreSQL using database URL
2. Append ```?sslmode=require``` (attempting this because SSL tab does not have equivalent option)
3. Click the Test button
4. See error: Connect failed: self signed certificate (details below)

**Expected behavior**
A successful connection equivalent (such as when using equivalent settings with pgAdmin)

**Error details**
Database connection error
Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
Error JSON: {
  "code": "DEPTH_ZERO_SELF_SIGNED_CERT"
}
Connection: {
  "server": "***",
  "engine": "postgres@dbgate-plugin-postgres",
  "useDatabaseUrl": "***",
  "sshMode": "userPassword",
  "sshKeyfile": "***",
  "databaseUrl": "***"
}
Platform: win32

**Version Information:**
 - OS: Windows
 - App Version: 5.0.6
 - Install: source installer
 - Type: application
 - Database engine: PostgreSQL

**Comment by janproch** [comment]
Hi, thanks for your feedback.

Why do you need to add sslmode=require prameter? It seems, that problem is with self signed certificate, does it work without this parameter? What error is reported without ?sslmode=require ?

**Comment by janproch** [comment]
I have tested it now agains heroku postgres database. It worked for me, I filled credentials on General page and than only I checked checkbox "Use SSL" on SSL tab

Without "Use SSL" checked, it returns following error:

error: no pg_hba.conf entry for host xxxx, user "yyyy", database "zzzz", no encryption

**Comment by woeye** [comment]
We are facing the same issue with DigitalOcean. DO enforces SSL mode and thus we cannot connect. What is weird, however, is that DO offers to download the CA but dbgate still complains about the self-signed certificate. Not sure about node.js, but in Java and Go it's possible to tell the runtime to simply accept self-signed certificates. Maybe there is an option in node.js like this, too?

**Comment by pmpetit** [comment]
Hi,
any news about this issue ?
i have the same, trying to connect to aiven db, where sslmode=require is mandatory.

**Comment by adamatti** [comment]
same issue here

**Comment by gabor-s** [comment]
Hi,

I managed to connect to Aiven with the following:
- don't check "Use SSL" on the SSL tab
- use database url on the General tab like this:
`postgres://user:password@host:port/database?sslmode=require&sslrootcert=path_to_aiven's_ca_on_your_machine`

**Comment by voodoodror** [comment]
Same issue here with RDS PostgreSQL

It's needed according to this article:
https://repost.aws/knowledge-center/aurora-postgresql-connect-iam

```bash
psql "host=$RDSHOST port=5432 sslmode=verify-full sslrootcert=global-bundle.pem dbname=postgres user=db_user_name password=$PGPASSWORD"
```

**Comment by dataspun** [comment]
Issue cannot be replicated with my current server environment.  Solutions provided above are reliable.  In particular, for cloud hosted PostgreSQL configured with Allow only SSL Connections, enabling the dbgate option Use SSL works as described above by @janproch
