### ISSUE TITLE
BUG: SQL Server, no way for tedious driver to connect to Named Instances?

### ISSUE THREAD

**Issue by tall-geese** [dbgate/dbgate#340]
I can't connect to a named instance using what should be the right format. 
The error I'll get is:
     *Error: Failed to connect to server\sql1:1433 - getaddrinfo ENOTFOUND server\sql1*

Connecting To: 
     **SQL Server 14.0.1**

The problem might be coming from the default port of 1433 is forced on you, but its not actually required.
Can you changed the port number to be *optional* in the event of a named instance?

![1](https://user-images.githubusercontent.com/12974904/183672919-78426d37-b6e0-4488-bd7f-40dc300d5a84.png)

After some struggling I did manage to connect using a native driver. I kept getting an error message
     *"[ODBC Driver Manager] DataSource name note found..."*

Its not very apparent that only these two drivers are supported.
So if someone reading this had my problem, just install one of these.

![2](https://user-images.githubusercontent.com/12974904/183677919-1c34ca5e-ab93-45cd-a2f7-8b5d7494b167.png)

**Comment by tudorels** [comment]
Hello, there is a solution? I have the same problem ...

**Comment by tudorels** [comment]
Error: Failed to connect to 10.0.0.7\erp:1433 - getaddrinfo ENOTFOUND 10.0.0.7\erp
    at Y.socketError (/Applications/DbGate.app/Contents/Resources/app.asar/packages/plugins/dbgate-plugin-mssql/dist/backend.js:158:198928)
    at /Applications/DbGate.app/Contents/Resources/app.asar/packages/plugins/dbgate-plugin-mssql/dist/backend.js:158:195710
    at GetAddrInfoReqWrap.callback (/Applications/DbGate.app/Contents/Resources/app.asar/packages/plugins/dbgate-plugin-mssql/dist/backend.js:180:175755)
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:79:17)

Error JSON: {
  "code": "ESOCKET"
}

Connection: {
  "server": "***",
  "engine": "mssql@dbgate-plugin-mssql",
  "sshMode": "userPassword",
  "sshKeyfile": "***",
  "user": "***",
  "password": "***",
  "trustServerCertificate": true
}

Platform: darwin

**Comment by tudorels** [comment]
Hello,
Did you manage to investigate this error?
To get the error you must try to connect to an sql named instance like ip\namedinstance (my connection 10.0.0.7\exdb)
I look forward to a solution. 
Thank you!

**Comment by janproch** [comment]
Released in 6.6.1
