### ISSUE TITLE
BUG: error connecting mysql database on AWS RDS (from mail feedback)

### ISSUE THREAD

**Issue by janproch** [dbgate/dbgate#351]
Trying to use dbgate to access a mysql database on AWS RDS via a bastion EC2 host.

I'm able to make the connection using MySQL workbench, but unable to replicate with DbGate. I looked on the website and didn't see any docs on troubleshooting connection issues.

Under SSH tunnel, what is the difference between Host and Bastion Host (Jump host)?

**Comment by bangouraboulaye** [comment]
Hi Jan,
did figure this issue, i am facing the same problem :-( 

trying to use dbgate to access a Postgres database on AWS RDS.
i got: 

Error in DB connection Error: Could not get driver from connection {"database":"***"}

**Comment by OneBadSanta** [comment]
Hey @janproch. I can't believe no one has answered this seemingly simple question yet. Doesn't seem like anyone is at home. Which is crazy because there seems to be a beta release every couple of days. 

I am trying to do the same thing as you and also wanted to know the answer to your question. 

I am getting some BS error with no actual error in the JSON response
....
Error JSON: {}
....

I saw this software and thought it was a great product but I just couldn't do anything with it, except connect to a local DB.

Were you ever to get access to RDS through a jumpbox?

**Comment by janproch** [comment]
If you could provide me access to your mysql db on aws, i could try to handle this. Better after my holiday, about april 15

**Comment by KeshariPiyush24** [comment]
I am getting below error when trying to connect to a droplet using SSH.

Same connection setting working on workbench.

Getting this Error:

```
Error
    at e.exports (/Applications/DbGate.app/Contents/Resources/app.asar/packages/api/dist/bundle.js:11:86455)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async process.<anonymous> (/Applications/DbGate.app/Contents/Resources/app.asar/packages/api/dist/bundle.js:456:324963)

Error JSON: {}

Connection: {
  "server": "***",
  "engine": "mysql@dbgate-plugin-mysql",
  "sshMode": "keyFile",
  "sshKeyfile": "***",
  "port": "3306",
  "user": "***",
  "password": "***",
  "defaultDatabase": "***",
  "singleDatabase": true,
  "displayName": "***",
  "connectionColor": "***",
  "useSshTunnel": true,
  "sshHost": "***",
  "sshPort": "***",
  "sshLogin": "***",
  "_id": "***",
  "unsaved": false
}

Platform: darwin
```

Provided SS FYR. Someone please help me fix this ASAP 🙏

<img width="965" alt="Screenshot 2023-03-26 at 6 22 50 PM" src="https://user-images.githubusercontent.com/18307180/227777013-26a6e9b7-ceec-4ca6-a4c4-005ed9af6333.png">

<img width="953" alt="Screenshot 2023-03-26 at 6 23 07 PM" src="https://user-images.githubusercontent.com/18307180/227777006-4b288894-dfd3-4e9e-b7e9-03345f6b4ca6.png">

<img width="286" alt="Screenshot 2023-03-26 at 6 16 30 PM" src="https://user-images.githubusercontent.com/18307180/227776893-fbb0a45a-b832-4ae0-b637-16e0686d44c0.png">

**Comment by janproch** [comment]
It works for me with current version, is this still active?
