### ISSUE TITLE
BUG: SSH tunnel has stopped resolving hostname

### ISSUE THREAD

**Issue by tvarsis** [dbgate/dbgate#456]
**Describe the bug**
A couple of versions back (I think in 5.1.6) hostname does not seems to be resolved any longer when used in SSH tunnel. Prior I could use the hostname instead of IP in the connection and it would resolve it from the SSH config file, same way that many programs do. It still works for other software to resolve by hostname, so I think something must have changed in DBGate which introduced this bug.

**To Reproduce**
1. In SSH tunnel, add a hostname instead of IP address that exists in your SSH config file.
2. Provide the rest of the information for the connection.
3. Press connect and get this error
4. 
```
Not connected
General
SSH Tunnel
SSL
 
Host
dev
Port
50500
Bastion host (Jump host)
SSH Authentication

Key file
Login
gsus
Private key file
/home/gsus/.ssh/id_rsa
Browse
Key file passphrase
  
Connect failed:  Show detail
Database connection error
Error
    at e.exports (/tmp/.mount_dbgateFw7yTN/resources/app.asar/packages/api/dist/bundle.js:9:90126)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async process.<anonymous> (/tmp/.mount_dbgateFw7yTN/resources/app.asar/packages/api/dist/bundle.js:184:262334)

Error JSON: {}

Connection: {
  "server": "***",
  "engine": "postgres@dbgate-plugin-postgres",
  "user": "***",
  "password": "***",
  "displayName": "***",
  "_id": "***",
  "status": "***",
  "sshMode": "keyFile",
  "sshPort": "***",
  "sshKeyfile": "***",
  "passwordMode": "saveEncrypted",
  "useSsl": false,
  "useSshTunnel": true,
  "sshHost": "***",
  "sshLogin": "***",
  "defaultDatabase": "***",
  "connectionColor": "***"
}

Platform: linux
```

**Expected behavior**
Would expect it to resolve the correct IP from the SSH config as it used to do and be able to connect to the db without providing the full IP address.

**Version Information (please complete the following information):**
 - OS: OpenSUSE Tumbleweed
 - App Version: 5.2.1
 - Install source: Appimage
 - Type: Application
 - Database engine: PostgreSQL 13

**Comment by tvarsis** [comment]
@janproch 5.2.9 fixed this issue as well. Closing it, and thank you!
