### ISSUE TITLE
MongoDB connection not working

### ISSUE THREAD

**Issue by holotrack** [dbgate/dbgate#487]
**Describe the bug**
When I configure MongoDB connection, it's not working. Looks like DBGate is trying to connect to 127.0.0.1 instead of configured values and failing with error:

`Connect failed: connect ECONNREFUSED 127.0.0.1:27017`

**To Reproduce**
Add new connection, fill config values and try to connect

**Expected behavior**
DBGate will connect to MongoDB

**Screenshots**
![image](https://user-images.githubusercontent.com/100580892/217069729-60b353f2-8ef0-4699-994b-53c2e56c99c3.png)

**Version Information (please complete the following information):**
 - OS: Docker-alpine
 - App Version 5.2.2
 - Install source Docker
 - Type - Web
 - Database engine: MongoDB
 
 Error details:
 
```
 MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at Timeout._onTimeout (/home/dbgate-docker/plugins/dbgate-plugin-mongo/dist/backend.js:9:850054)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)

Error JSON: {
  "reason": {
    "type": "ReplicaSetNoPrimary",
    "servers": {},
    "stale": false,
    "compatible": true,
    "heartbeatFrequencyMS": 10000,
    "localThresholdMS": 15,
    "setName": "cluster",
    "maxSetVersion": 1,
    "maxElectionId": "7fffffff0000000000000002",
    "commonWireVersion": 13
  }
}

Connection: {
  "server": "***",
  "engine": "mongo@dbgate-plugin-mongo",
  "sshMode": "userPassword",
  "sshKeyfile": "***",
  "user": "***",
  "password": "***",
  "defaultDatabase": "***",
  "displayName": "***"
}

Platform: linux
```

**Comment by holotrack** [comment]
I finally connected with URL settings:

```
mongodb://<credentials>@mongo-service:27017/?directConnection=true
```

that `directConnection` was missing but still it should work with non url settings

**Comment by janproch** [comment]
Thanks for the feedback

In normal situations connection works also without URL, but probably there is some specific configuration in your case. However, adding directConnection=true by default is not good solution

**Comment by jxfruit** [comment]
> directConnection=true

awsome
