### ISSUE TITLE
BUG: ver  5.2.3 npm version no longer loads (HOTFIX)

### ISSUE THREAD

**Issue by dcroal** [dbgate/dbgate#508]
I just updated my npm DbGate to ver 5.2.3 using the instructions from https://www.npmjs.com/package/dbgate-serve as I have done many times before. This time I got the following error:

~$ /usr/local/bin/dbgate-serve 
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'dbgate-datalib'
Require stack:
- /usr/local/lib/node_modules/dbgate-serve/node_modules/dbgate-api/src/shell/dataDuplicator.js
- /usr/local/lib/node_modules/dbgate-serve/node_modules/dbgate-api/src/shell/index.js
- /usr/local/lib/node_modules/dbgate-serve/node_modules/dbgate-api/src/index.js
- /usr/local/lib/node_modules/dbgate-serve/bin/dbgate-serve.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/dbgate-serve/node_modules/dbgate-api/src/shell/dataDuplicator.js:7:28)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/dbgate-serve/node_modules/dbgate-api/src/shell/dataDuplicator.js',
    '/usr/local/lib/node_modules/dbgate-serve/node_modules/dbgate-api/src/shell/index.js',
    '/usr/local/lib/node_modules/dbgate-serve/node_modules/dbgate-api/src/index.js',
    '/usr/local/lib/node_modules/dbgate-serve/bin/dbgate-serve.js'
  ]
}

I'm using Debian 11 via crostini on ChromeOS. Thanks.

**Comment by janproch** [comment]
Thanks for reporting

Fixed in alpha version (5.2.4-alpha.1), will be released probably on Sunday as hotfix
