### ISSUE TITLE
BUG: Getting Unknown error while connecting to a droplet over SSH

### ISSUE THREAD

**Issue by KeshariPiyush24** [dbgate/dbgate#526]
I am getting some error when trying to connect to a droplet using SSH. Same connection setting is working on workbench.

Getting this Error:

```
Error
    at e.exports (/Applications/DbGate.app/Contents/Resources/app.asar/packages/api/dist/bundle.js:11:86455)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async process.<anonymous> (/Applications/DbGate.app/Contents/Resources/app.asar/packages/api/dist/bundle.js:456:324963)

Error JSON: {}

Connection: {
  "server": "***",
  "engine": "mysql@dbgate-plugin-mysql",
  "sshMode": "keyFile",
  "sshKeyfile": "***",
  "port": "3306",
  "user": "***",
  "password": "***",
  "defaultDatabase": "***",
  "singleDatabase": true,
  "displayName": "***",
  "connectionColor": "***",
  "useSshTunnel": true,
  "sshHost": "***",
  "sshPort": "***",
  "sshLogin": "***",
  "_id": "***",
  "unsaved": false
}

Platform: darwin
```

Provided SS FYR. Someone please help me fix this ASAP 🙏

<img width="965" alt="Screenshot 2023-03-26 at 6 22 50 PM" src="https://user-images.githubusercontent.com/18307180/227777013-26a6e9b7-ceec-4ca6-a4c4-005ed9af6333.png">

<img width="953" alt="Screenshot 2023-03-26 at 6 23 07 PM" src="https://user-images.githubusercontent.com/18307180/227777006-4b288894-dfd3-4e9e-b7e9-03345f6b4ca6.png">

<img width="286" alt="Screenshot 2023-03-26 at 6 16 30 PM" src="https://user-images.githubusercontent.com/18307180/227776893-fbb0a45a-b832-4ae0-b637-16e0686d44c0.png">

**Comment by stouch** [comment]
I got the same error since last upgrade

**Comment by stouch** [comment]
I found an ugly way to solve this : Move your private key in `/home/<homedir>/snap/dbgate/current` and then change the permission to 744, then you will be able to use this key in a connection... Hopping for a fix soon.

**Comment by rileysiemens** [comment]
Bumping because I also have this issue.

**Comment by JackThird** [comment]
> Bumping because I also have this issue, but with the appimage

same here
