### ISSUE TITLE
BUG: Unable to load DB, errors about unable to set headers after being sent to the client

### ISSUE THREAD

**Issue by LunarTwilight** [dbgate/dbgate#568]
**Describe the bug**
When I open dbgate it's stuck on "loading database structure" and I have the following error in my logs:
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:399:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at ServerResponse.header (/usr/lib/node_modules/dbgate-serve/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/usr/lib/node_modules/dbgate-serve/node_modules/express/lib/response.js:174:12)
    at unauthorizedResponse (/usr/lib/node_modules/dbgate-serve/node_modules/dbgate-api/src/controllers/auth.js:29:30)
    at authMiddleware (/usr/lib/node_modules/dbgate-serve/node_modules/dbgate-api/src/controllers/auth.js:45:12)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/dbgate-serve/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/lib/node_modules/dbgate-serve/node_modules/express/lib/router/index.js:328:13)
    at /usr/lib/node_modules/dbgate-serve/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/usr/lib/node_modules/dbgate-serve/node_modules/express/lib/router/index.js:346:12)
```

**To Reproduce**
1. Open dbgate
2. Attempt to open DB
3. Error happens

**Expected behavior**
DB to load as expected

**Screenshots**

**Version Information (please complete the following information):**
 - OS: Ubuntu
 - App Version: 5.2.6
 - Install source: NPM
 - Type: Web
 - Database engine: SQLite

**Comment by LunarTwilight** [comment]
Looking at my logs, I thought that #517 had been resolved (I didn't see it when I viewed one of my logs), but I looked at the my logs in a different place and the problem mentioned in that issue is still happening, so it could be that issue, or this issue, or both, that's causing my DB to not be able to be opened. (both have been happening for a while now)

**Comment by argaar** [comment]
I can confirm the bug, it also happened to me with npm deploy and also withdocker ones.
It happens with Basic Auth and with AD Auth as well, the only workaround I've found at the moment is to use nginx as reverse proxy (I'm using the docker version) with an htpasswd file (that would ends up to mimic the Basic Auth)

My goal is to use it in production but without AD Auth (however is not a problem strictly related to AD) this won't be possibile

**Comment by LunarTwilight** [comment]
Yep, disabling basic auth got rid of the error for me too.

**Comment by LunarTwilight** [comment]
@argaar does this error still happen for you? It seems to have stopped for me, even with basic auth enabled (tho I get another error instead - #934), so I was thinking about closing out this issue.
