### ISSUE TITLE
BUG: Issue connecting to MySQL DB with cleartext plugin.

### ISSUE THREAD

**Issue by sennpy** [dbgate/dbgate#629]
**Describe the bug**
```

Error: Server requests authentication using unknown plugin mysql_clear_password. See TODO: add plugins doco here on how to configure or author authentication plugins.
    at Object.authSwitchRequest (/Applications/DbGate.app/Contents/Resources/app.asar/packages/plugins/dbgate-plugin-mysql/dist/backend.js:289:299126)
    at _.handshakeResult (/Applications/DbGate.app/Contents/Resources/app.asar/packages/plugins/dbgate-plugin-mysql/dist/backend.js:11:289543)
    at _.execute (/Applications/DbGate.app/Contents/Resources/app.asar/packages/plugins/dbgate-plugin-mysql/dist/backend.js:3:15525)
    at A.handlePacket (/Applications/DbGate.app/Contents/Resources/app.asar/packages/plugins/dbgate-plugin-mysql/dist/backend.js:11:96686)
    at a.onPacket (/Applications/DbGate.app/Contents/Resources/app.asar/packages/plugins/dbgate-plugin-mysql/dist/backend.js:11:91215)
    at a.executeStart (/Applications/DbGate.app/Contents/Resources/app.asar/packages/plugins/dbgate-plugin-mysql/dist/backend.js:11:197928)
    at TLSSocket.<anonymous> (/Applications/DbGate.app/Contents/Resources/app.asar/packages/plugins/dbgate-plugin-mysql/dist/backend.js:11:95344)
    at TLSSocket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)

Error JSON: {
  "code": "AUTH_SWITCH_PLUGIN_ERROR",
  "fatal": true
}

Connection: {
  "server": "***",
  "engine": "mysql@dbgate-plugin-mysql",
  "sshMode": "userPassword",
  "sshKeyfile": "***",
  "user": "***",
  "password": "***",
  "isReadOnly": true,
  "port": "3306",
  "authType": "hostPort",
  "passwordMode": "saveEncrypted",
  "useSshTunnel": false,
  "useSsl": true
}

Platform: darwin
```

**To Reproduce**
1. Try connecting to MySQL server requiring cleartext plugin

**Expected behavior**
Expecting to connect to the server

**Screenshots**
connection details is probably the most useful piece of info

**Version Information (please complete the following information):**
 - OS: Mac
 - App Version 5.2.6
 - Install source installer
 - Type - Application
 - Database engine: MySQL

**Comment by ProjectInfinity** [comment]
Hi, please try [v5.2.8-beta.4](https://github.com/dbgate/dbgate/releases/tag/v5.2.8-beta.4) when it is ready in a couple of minutes.

It contains various general bug fixes but more importantly it contains an upgrade of the driver used for mysql.

**Comment by ProjectInfinity** [comment]
Hi, please test the following beta.

https://github.com/dbgate/dbgate/releases/tag/v5.2.8-beta.5

It contains an updated mysql driver that should resolve this issue.
