### ISSUE TITLE
BUG: Cannot enable app in web app (node version)

### ISSUE THREAD

**Issue by ezwelty** [dbgate/dbgate#707]
**Describe the bug**
Right-clicking on an app name and clicking "Enable on current database" has no effect. Likewise, navigating to a column with a foreign key reference, clicking on [...] > Lookup from {table} > Customize, the changes made do not take effect, regardless of whether the "Target application" is an existing one or "(New application linked to current DB)".

**To Reproduce**
(see above)

**Expected behavior**
The app can be edited and enabled as on the desktop version.

**Screenshots**
Here is the error, copied from the browser console, that is thrown:
```
Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at api.ts:124:37
    at Generator.next (<anonymous>)
    at a (tslib.es6.js:73:58)
```

**Comment by ezwelty** [comment]
Closing as this is deprecated. The interface for applications has changed substantially by now (v6.6.11).
