### ISSUE TITLE
AWS RDS Connection Failure

### ISSUE THREAD

**Issue by josh-thurston** [dbgate/dbgate#712]
I have been able to establish a connection to an AWS RDS (postgres) database from four other tools, but I cannot get it to work with DBGate.  I get a Database Connection Error.  I think it could possibly be the plugin?

error: no pg_hba.conf entry for host "myhostinfo", user "myusername", database "mydatabase_name", no encryption
    at t.Parser.parseErrorMessage (/Applications/DbGate.app/Contents/Resources/app.asar/packages/plugins/dbgate-plugin-postgres/dist/backend.js:17:213256)
    at t.Parser.handlePacket (/Applications/DbGate.app/Contents/Resources/app.asar/packages/plugins/dbgate-plugin-postgres/dist/backend.js:17:209896)
    at t.Parser.parse (/Applications/DbGate.app/Contents/Resources/app.asar/packages/plugins/dbgate-plugin-postgres/dist/backend.js:17:208551)
    at Socket.<anonymous> (/Applications/DbGate.app/Contents/Resources/app.asar/packages/plugins/dbgate-plugin-postgres/dist/backend.js:9:142674)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)

Error JSON: {
  "length": 160,
  "name": "error",
  "severity": "FATAL",
  "code": "28000",
  "file": "auth.c",
  "line": "543",
  "routine": "ClientAuthentication"
}

Connection: {
  "server": "***",
  "engine": "postgres@dbgate-plugin-postgres",
  "sshMode": "userPassword",
  "sshKeyfile": "***",
  "user": "***",
  "password": "***",
  "defaultDatabase": "***",
  "displayName": "***",
  "singleDatabase": true,
  "authType": "hostPort",
  "databaseUrl": "***",
  "passwordMode": "saveEncrypted",
  "port": "5432"
}

Platform: darwin

**Comment by janproch** [comment]
For AWS RDS, you have to check "Use SSL" checkbox on SSL tab, when creating connection
