### ISSUE TITLE
BUG: Connect via ssh tunnel failed

### ISSUE THREAD

**Issue by syntaxys** [dbgate/dbgate#757]
**Describe the bug**
Can't connect to a specific MySQL host via ssh tunnel while it is possible with i. e. the app „Sequel Ace“ on the same machine. Other tunneled connections work without a problem in DbGate. Is there a way to debug this? I don't have access to the host providers log files.

**Log details**
```
Error
    at e.exports (/Applications/DbGate.app/Contents/Resources/app.asar/packages/api/dist/bundle.js:11:86455)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async process.<anonymous> (/Applications/DbGate.app/Contents/Resources/app.asar/packages/api/dist/bundle.js:456:325634)

Error JSON: {}

Connection: {
  "server": "***",
  "engine": "mariadb@dbgate-plugin-mysql",
  "sshMode": "keyFile",
  "sshKeyfile": "***",
  "displayName": "***",
  "connectionColor": "***",
  "useSshTunnel": true,
  "sshHost": "***",
  "sshLogin": "***",
  "sshKeyfilePassword": "***",
  "_id": "***",
  "unsaved": false,
  "user": "***",
  "defaultDatabase": "***",
  "singleDatabase": false,
  "password": "***",
  "parent": "***",
  "passwordMode": "saveRaw",
  "sshPassword": "***"
}

Platform: darwin
```

**Version Information:**
 - OS: MacOS Big Sur
 - App Version 5.2.7
 - Install source: installer
 - Database engine: MySQL

**Comment by ProjectInfinity** [comment]
Please try the following Beta https://github.com/dbgate/dbgate/releases/tag/v5.2.9-beta.1

**Comment by 0rax** [comment]
Had a similar issue on Linux with SSH tunneling no longer working. Tried the latest beta (`v5.2.9-beta.4`) which fixed the issue for me.

**Comment by gordonlau** [comment]
The issue still persists for Linux.

* OS: Ubuntu Linux 24.04
* App Version: 5.3.0
* Installation: AppImage
* Engine: PostgreSQL

Installing older version does not work anymore. The error is still the same.

```bash
Error
    at e.exports (/tmp/.mount_dbgateWrc88x/resources/app.asar/packages/api/dist/bundle.js:2:2117465)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async process.<anonymous> (/tmp/.mount_dbgateWrc88x/resources/app.asar/packages/api/dist/bundle.js:2:2076560)

Error JSON: {}

Connection: {
  "server": "***",
  "engine": "postgres@dbgate-plugin-postgres",
  "sshMode": "keyFile",
  "sshKeyfile": "***",
  "user": "***",
  "defaultDatabase": "***",
  "displayName": "***",
  "connectionColor": "***",
  "password": "***",
  "useSshTunnel": true,
  "sshHost": "***",
  "sshLogin": "***",
  "_id": "***",
  "unsaved": false,
  "singleDatabase": true
}

Platform: linux
```

**Comment by gordonlau** [comment]
Just to document for people who want to use SSH Tunnel with DBGate but is currently blocking by this issue.

It is perfectly working to use `ssh` command to create the ssh tunnel and set the tunnel to connect to the local port `5433`.

```
ssh -NfL 5433:<db-host>:5432 <ssh-host>
```

You can also use `autossh` if you want to maintain the tunnel automatically.

**Comment by josbeir** [comment]
Check if
```
127.0.0.1 localhost
```

is missing in your /ets/hosts file. It was missing for me on Arch, it started working after adding it (using the flatpak version). 

Authentication mode: Username & password
Didn't check Agent / key mode.

**Comment by nicnab** [comment]
I have the same error right now on one of two Manjaro KDE boxes using DBGate 6.1.2. One machine works, the other doesn't anymore. No /tmp leftovers and other than that the same configuration with ssh agent that unlocks the key at login.

Here's the error:

```
Connect failed:  Failed to connect to agent Show detail

Database connection error
Error: Failed to connect to agent
    at e.exports (/tmp/.mount_dbgatezXlKcH/resources/app.asar/packages/api/dist/bundle.js:2:1486758)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async process.<anonymous> (/tmp/.mount_dbgatezXlKcH/resources/app.asar/packages/api/dist/bundle.js:2:1435703)

Error JSON: {}

Connection: {
  "server": "***",
  "engine": "mariadb@dbgate-plugin-mysql",
  "sshMode": "agent",
  "sshKeyfile": "***",
  "user": "***",
  "password": "***",
  "displayName": "***",
  "useSshTunnel": true,
  "sshHost": "***",
  "sshLogin": "***",
  "unsaved": false,
  "_id": "***",
  "sshPassword": "***",
  "requestDbList": false
}

Platform: linux

```

**Comment by janproch** [comment]
Should be fixed in 6.1.3

Try to adjust Local host address for SSH connections in Connection settings

![Image](https://github.com/user-attachments/assets/2c5aab42-14b9-4b67-a628-12f5511c874d)

**Comment by nicnab** [comment]
I'm pretty sure that wasn't the problem in my case. I got it to work by rsyncing all the settings of all three settings folders from the working machine to the one with the error. But that way I wasn't sure what really caused it, of course.
