### ISSUE TITLE
GLIBC_2.29' not found and i have 2.31

### ISSUE THREAD

**Issue by MFdanGM** [dbgate/dbgate#794]
{"pid":62819,"caller":"databaseConnections","name":"main","level":50,"msg":"Error in database connection cdfa36f0-03c6-11ef-8ea3-bde43d5fcb86, database storage.db: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /snap/dbgate/421/resources/app.asar.unpacked/node_modules/better-sqlite3/build/Release/better_sqlite3.node)","time":1716196298495}

Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /snap/dbgate/421/resources/app.asar.unpacked/node_modules/better-sqlite3/build/Release/better_sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
    at Module._extensions..node (node:internal/modules/cjs/loader:1489:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2441)
    at Module.load (node:internal/modules/cjs/loader:1214:32)
    at Module._load (node:internal/modules/cjs/loader:1030:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1242:19)
    at require (node:internal/modules/helpers:176:18)
    at bindings (/snap/dbgate/421/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at new Database (/snap/dbgate/421/resources/app.asar/node_modules/better-sqlite3/lib/database.js:48:64)

Error JSON: {
  "code": "ERR_DLOPEN_FAILED"
}

Connection: {
  "engine": "sqlite@dbgate-plugin-sqlite",
  "databaseFile": "***",
  "displayName": "***",
  "connectionColor": "***",
  "singleDatabase": true,
  "defaultDatabase": "***",
  "unsaved": false,
  "_id": "***"
}

**Comment by MFdanGM** [comment]
AppImage works fine. Thanks a lot. Great app!
