### ISSUE TITLE
Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by Volodymyr0587** [dbgate/dbgate#804]
Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /snap/dbgate/421/resources/app.asar.unpacked/node_modules/better-sqlite3/build/Release/better_sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
    at Module._extensions..node (node:internal/modules/cjs/loader:1489:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2441)
    at Module.load (node:internal/modules/cjs/loader:1214:32)
    at Module._load (node:internal/modules/cjs/loader:1030:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1242:19)
    at require (node:internal/modules/helpers:176:18)
    at bindings (/snap/dbgate/421/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at new Database (/snap/dbgate/421/resources/app.asar/node_modules/better-sqlite3/lib/database.js:48:64)

Error JSON: {
  "code": "ERR_DLOPEN_FAILED"
}

Connection: {
  "server": "***",
  "engine": "sqlite@dbgate-plugin-sqlite",
  "databaseFile": "***"
}

Platform: linux

**Comment by ProjectInfinity** [comment]
Please use the .deb file, AppImage or flatpak. There seems to be an issue regarding snap.

**Comment by Volodymyr0587** [comment]
@ProjectInfinity Thank you. With .deb everything works now.
