### ISSUE TITLE
BUG: Cannot connect to MariaDB on Azure

### ISSUE THREAD

**Issue by llimos** [dbgate/dbgate#85]
**Describe the bug**
Failed to connect to a MariaDB instance on Azure. From "Test Connection" button I get "Connect failed:  An internal error has occurred. Please retry or report your issues."

**To Reproduce**
1. Spin up a MariaDB database on Microsoft Azure (*.mariadb.database.azure.com)
2. In DbGate, Add a new MySQL/MariaDB connection and enter all the details
3. Click Test Connection
4. Get generic error message
I tried various different SSL options, enabled/disabled, with/without CA cert, it made no difference

**Expected behavior**
Connection succeeds

**Screenshots**
![image](https://user-images.githubusercontent.com/5158621/115699630-7afc0980-a36e-11eb-8f58-6fb26bf0a356.png)

**Version Information (please complete the following information):**
 - OS: Windows 10
 - App Version: 4.1.9
 - Install source: Installer
 - Type: Application
 - Database engine: MariaDB

**Additional context**
When running it from the console I get the following output:

```
Loading module dbgate-plugin-mysql from C:\Users\shimonl\AppData\Local\Programs\dbgate\resources\app.asar\packages\plugins\dbgate-plugin-mysql\dist\backend.js
Error: An internal error has occurred. Please retry or report your issues.
    at h.asError (C:\Users\shimonl\AppData\Local\Programs\dbgate\resources\app.asar\packages\plugins\dbgate-plugin-mysql\dist\backend.js:1:9129)
    at c.execute (C:\Users\shimonl\AppData\Local\Programs\dbgate\resources\app.asar\packages\plugins\dbgate-plugin-mysql\dist\backend.js:1:16605)
    at N.handlePacket (C:\Users\shimonl\AppData\Local\Programs\dbgate\resources\app.asar\packages\plugins\dbgate-plugin-mysql\dist\backend.js:9:95486)
    at o.onPacket (C:\Users\shimonl\AppData\Local\Programs\dbgate\resources\app.asar\packages\plugins\dbgate-plugin-mysql\dist\backend.js:9:90195)
    at o.executeStart (C:\Users\shimonl\AppData\Local\Programs\dbgate\resources\app.asar\packages\plugins\dbgate-plugin-mysql\dist\backend.js:9:145711)
    at TLSSocket.<anonymous> (C:\Users\shimonl\AppData\Local\Programs\dbgate\resources\app.asar\packages\plugins\dbgate-plugin-mysql\dist\backend.js:9:94262)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10) {
  code: undefined,
  errno: 9999,
  sqlState: '28000',
  sqlMessage: 'An internal error has occurred. Please retry or report your issues.\u0000'
}
```

**Comment by janproch** [comment]
Thanks for error report
I tried to connect to MariaDB versions 10.2 and 10.3, which should be used on Azure cloud acording to https://docs.microsoft.com/en-us/azure/mariadb/concepts-supported-versions, and both worked
It is possible to send me access to some testing MariaDB database on Azure cloud, to debug this problem?

**Comment by llimos** [comment]
I'd like to help but it's not so simple because I'd also need to whitelist your IP address.
You can probably set one up using free Azure credits you get when you sign up.
Or, send me some commands to try from whatever underlying libraries you're using?

**Comment by llimos** [comment]
I discovered the issue. Azure requires the username to have @<instancename> at the end. When I added that it worked 😃 
Though, I do think it needs a better error message than 'An internal error occurred'. I don't know what message the server returned in this case, but maybe display whatever the server sent?
