### ISSUE TITLE
BUG: Cannot build dev environment on windows

### ISSUE THREAD

**Issue by AnisRouane67** [dbgate/dbgate#854]
**Describe the bug**
When using yarn to install dependencies, the process fails at the linking step.

**To Reproduce**
1. Fork the project and clone the repo on windows (11 if it matters)
2. Run yarn command in the project folder
3. BOOM! it fails.

**Version Information (please complete the following information):**
 - OS: Windows 11

** build.log: **

```
# This file contains the result of Yarn building a package (dbgate-all@workspace:.)
# Script name: postinstall

patch-package 6.5.1
Applying patches...
No patch files found
dbgate-plugin-csv      │ asset [1m[32mfrontend.js[39m[22m 1.21 KiB [1m[33m[compared for emit][39m[22m [1m[32m[minimized][39m[22m (name: app)
dbgate-plugin-csv      │ runtime modules 670 bytes 3 modules
dbgate-plugin-csv      │ [1m./index.js[39m[22m 1.74 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-csv      │ 
dbgate-plugin-csv      │ [1m[33mWARNING[39m[22m in [1mconfiguration
dbgate-plugin-csv      │ The [1m[31m'mode' option has not been set[39m[22m[1m, webpack will fallback to 'production' for this value.
dbgate-plugin-csv      │ [1m[32mSet 'mode' option to 'development' or 'production'[39m[22m[1m to enable defaults for each environment.
dbgate-plugin-csv      │ You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/[39m[22m
dbgate-plugin-csv      │ 
dbgate-plugin-csv      │ webpack 5.93.0 compiled with [1m[33m1 warning[39m[22m in 236 ms
dbgate-plugin-excel    │ asset [1m[32mfrontend.js[39m[22m 1.32 KiB [1m[33m[compared for emit][39m[22m [1m[32m[minimized][39m[22m (name: app)
dbgate-plugin-excel    │ runtime modules 670 bytes 3 modules
dbgate-plugin-excel    │ [1m./index.js[39m[22m 2.02 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-excel    │ 
dbgate-plugin-excel    │ [1m[33mWARNING[39m[22m in [1mconfiguration
dbgate-plugin-excel    │ The [1m[31m'mode' option has not been set[39m[22m[1m, webpack will fallback to 'production' for this value.
dbgate-plugin-excel    │ [1m[32mSet 'mode' option to 'development' or 'production'[39m[22m[1m to enable defaults for each environment.
dbgate-plugin-excel    │ You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/[39m[22m
dbgate-plugin-excel    │ 
dbgate-plugin-excel    │ webpack 5.93.0 compiled with [1m[33m1 warning[39m[22m in 247 ms
dbgate-plugin-mongo    │ asset [1m[32mfrontend.js[39m[22m 75.1 KiB [1m[33m[compared for emit][39m[22m [1m[32m[minimized][39m[22m (name: app) 1 related asset
dbgate-plugin-mongo    │ runtime modules 1.25 KiB 6 modules
dbgate-plugin-mongo    │ cacheable modules 540 KiB
dbgate-plugin-mongo    │   modules by path [1m./*.js[39m[22m 6.15 KiB
dbgate-plugin-mongo    │     [1m./index.js[39m[22m 341 bytes [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-mongo    │     [1m./driver.js[39m[22m 3.08 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-mongo    │     [1m./profilerFunctions.js[39m[22m 2.64 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-mongo    │     [1m./Dumper.js[39m[22m 109 bytes [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-mongo    │   modules by path [1m../../../../node_modules/[39m[22m 534 KiB
dbgate-plugin-mongo    │     [1m../../../../node_modules/dbgate-query-splitter/lib/options.js[39m[22m 2.51 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-mongo    │     [1m../../../../node_modules/lodash/lodash.js[39m[22m 531 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-mongo    │ 
dbgate-plugin-mongo    │ [1m[33mWARNING[39m[22m in [1mconfiguration
dbgate-plugin-mongo    │ The [1m[31m'mode' option has not been set[39m[22m[1m, webpack will fallback to 'production' for this value.
dbgate-plugin-mongo    │ [1m[32mSet 'mode' option to 'development' or 'production'[39m[22m[1m to enable defaults for each environment.
dbgate-plugin-mongo    │ You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/[39m[22m
dbgate-plugin-mongo    │ 
dbgate-plugin-mongo    │ webpack 5.93.0 compiled with [1m[33m1 warning[39m[22m in 1777 ms
dbgate-plugin-mssql    │ asset [1m[32mfrontend.js[39m[22m 8.63 KiB [1m[33m[compared for emit][39m[22m [1m[32m[minimized][39m[22m (name: app)
dbgate-plugin-mssql    │ runtime modules 937 bytes 4 modules
dbgate-plugin-mssql    │ cacheable modules 12.4 KiB
dbgate-plugin-mssql    │   [1m./index.js[39m[22m 78 bytes [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-mssql    │   [1m./driver.js[39m[22m 4.42 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-mssql    │   [1m./MsSqlDumper.js[39m[22m 5.4 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-mssql    │   [1m../../../../node_modules/dbgate-query-splitter/lib/options.js[39m[22m 2.51 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-mssql    │ 
dbgate-plugin-mssql    │ [1m[33mWARNING[39m[22m in [1mconfiguration
dbgate-plugin-mssql    │ The [1m[31m'mode' option has not been set[39m[22m[1m, webpack will fallback to 'production' for this value.
dbgate-plugin-mssql    │ [1m[32mSet 'mode' option to 'development' or 'production'[39m[22m[1m to enable defaults for each environment.
dbgate-plugin-mssql    │ You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/[39m[22m
dbgate-plugin-mssql    │ 
dbgate-plugin-mssql    │ webpack 5.93.0 compiled with [1m[33m1 warning[39m[22m in 382 ms
dbgate-plugin-mysql    │ asset [1m[32mfrontend.js[39m[22m 6.4 KiB [1m[33m[compared for emit][39m[22m [1m[32m[minimized][39m[22m (name: app)
dbgate-plugin-mysql    │ runtime modules 937 bytes 4 modules
dbgate-plugin-mysql    │ cacheable modules 9.22 KiB
dbgate-plugin-mysql    │   modules by path [1m./*.js[39m[22m 6.23 KiB
dbgate-plugin-mysql    │     [1m./index.js[39m[22m 109 bytes [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-mysql    │     [1m./drivers.js[39m[22m 3.81 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-mysql    │     [1m./Dumper.js[39m[22m 2.31 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-mysql    │   modules by path [1m../../../../node_modules/[39m[22m 2.99 KiB
dbgate-plugin-mysql    │     [1m../../../../node_modules/dbgate-query-splitter/lib/options.js[39m[22m 2.51 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-mysql    │     [1m../../../../node_modules/lodash/isArray.js[39m[22m 488 bytes [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-mysql    │ 
dbgate-plugin-mysql    │ [1m[33mWARNING[39m[22m in [1mconfiguration
dbgate-plugin-mysql    │ The [1m[31m'mode' option has not been set[39m[22m[1m, webpack will fallback to 'production' for this value.
dbgate-plugin-mysql    │ [1m[32mSet 'mode' option to 'development' or 'production'[39m[22m[1m to enable defaults for each environment.
dbgate-plugin-mysql    │ You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/[39m[22m
dbgate-plugin-mysql    │ 
dbgate-plugin-mysql    │ webpack 5.93.0 compiled with [1m[33m1 warning[39m[22m in 347 ms
dbgate-plugin-oracle   │ asset [1m[32mfrontend.js[39m[22m 5.16 KiB [1m[33m[compared for emit][39m[22m [1m[32m[minimized][39m[22m (name: app)
dbgate-plugin-oracle   │ runtime modules 937 bytes 4 modules
dbgate-plugin-oracle   │ cacheable modules 10 KiB
dbgate-plugin-oracle   │   [1m./index.js[39m[22m 110 bytes [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-oracle   │   [1m./drivers.js[39m[22m 3.66 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-oracle   │   [1m./Dumper.js[39m[22m 3.76 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-oracle   │   [1m../../../../node_modules/dbgate-query-splitter/lib/options.js[39m[22m 2.51 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-oracle   │ 
dbgate-plugin-oracle   │ [1m[33mWARNING[39m[22m in [1mconfiguration
dbgate-plugin-oracle   │ The [1m[31m'mode' option has not been set[39m[22m[1m, webpack will fallback to 'production' for this value.
dbgate-plugin-oracle   │ [1m[32mSet 'mode' option to 'development' or 'production'[39m[22m[1m to enable defaults for each environment.
dbgate-plugin-oracle   │ You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/[39m[22m
dbgate-plugin-oracle   │ 
dbgate-plugin-oracle   │ webpack 5.93.0 compiled with [1m[33m1 warning[39m[22m in 340 ms
dbgate-plugin-postgres │ asset [1m[32mfrontend.js[39m[22m 8.1 KiB [1m[33m[compared for emit][39m[22m [1m[32m[minimized][39m[22m (name: app)
dbgate-plugin-postgres │ runtime modules 937 bytes 4 modules
dbgate-plugin-postgres │ cacheable modules 12.1 KiB
dbgate-plugin-postgres │   [1m./index.js[39m[22m 112 bytes [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-postgres │   [1m./drivers.js[39m[22m 6.15 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-postgres │   [1m./Dumper.js[39m[22m 3.31 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-postgres │   [1m../../../../node_modules/dbgate-query-splitter/lib/options.js[39m[22m 2.51 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-postgres │ 
dbgate-plugin-postgres │ [1m[33mWARNING[39m[22m in [1mconfiguration
dbgate-plugin-postgres │ The [1m[31m'mode' option has not been set[39m[22m[1m, webpack will fallback to 'production' for this value.
dbgate-plugin-postgres │ [1m[32mSet 'mode' option to 'development' or 'production'[39m[22m[1m to enable defaults for each environment.
dbgate-plugin-postgres │ You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/[39m[22m
dbgate-plugin-postgres │ 
dbgate-plugin-postgres │ webpack 5.93.0 compiled with [1m[33m1 warning[39m[22m in 398 ms
dbgate-plugin-redis    │ asset [1m[32mfrontend.js[39m[22m 227 KiB [1m[33m[compared for emit][39m[22m [1m[32m[minimized][39m[22m (name: app) 1 related asset
dbgate-plugin-redis    │ runtime modules 1.25 KiB 6 modules
dbgate-plugin-redis    │ modules by path [1m../../../../node_modules/lodash/*.js[39m[22m 705 KiB 229 modules
dbgate-plugin-redis    │ modules by path [1m../../../../packages/[39m[22m 178 KiB 34 modules
dbgate-plugin-redis    │ modules by path [1m../../../../node_modules/es-errors/*.js[39m[22m 524 bytes 7 modules
dbgate-plugin-redis    │ modules by path [1m./*.js[39m[22m 2.54 KiB 3 modules
dbgate-plugin-redis    │ modules by path [1m../../../../node_modules/dbgate-query-splitter/lib/*.js[39m[22m 18.2 KiB 3 modules
dbgate-plugin-redis    │ modules by path [1m../../../../node_modules/uuid/[39m[22m 5.29 KiB 3 modules
dbgate-plugin-redis    │ modules by path [1m../../../../node_modules/jsonify/[39m[22m 8.84 KiB 3 modules
dbgate-plugin-redis    │ modules by path [1m../../../../node_modules/object-keys/*.js[39m[22m 4.36 KiB 3 modules
dbgate-plugin-redis    │ modules by path [1m../../../../node_modules/json-stable-stringify/[39m[22m 2.71 KiB 2 modules
dbgate-plugin-redis    │ modules by path [1m../../../../node_modules/call-bind/*.js[39m[22m 1.42 KiB 2 modules
dbgate-plugin-redis    │ modules by path [1m../../../../node_modules/function-bind/*.js[39m[22m 2.12 KiB 2 modules
dbgate-plugin-redis    │ modules by path [1m../../../../node_modules/has-symbols/*.js[39m[22m 2.13 KiB 2 modules
dbgate-plugin-redis    │ + 9 modules
dbgate-plugin-redis    │ 
dbgate-plugin-redis    │ [1m[33mWARNING[39m[22m in [1mconfiguration
dbgate-plugin-redis    │ The [1m[31m'mode' option has not been set[39m[22m[1m, webpack will fallback to 'production' for this value.
dbgate-plugin-redis    │ [1m[32mSet 'mode' option to 'development' or 'production'[39m[22m[1m to enable defaults for each environment.
dbgate-plugin-redis    │ You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/[39m[22m
dbgate-plugin-redis    │ 
dbgate-plugin-redis    │ webpack 5.93.0 compiled with [1m[33m1 warning[39m[22m in 3379 ms
dbgate-plugin-sqlite   │ asset [1m[32mfrontend.js[39m[22m 4.55 KiB [1m[33m[compared for emit][39m[22m [1m[32m[minimized][39m[22m (name: app)
dbgate-plugin-sqlite   │ runtime modules 937 bytes 4 modules
dbgate-plugin-sqlite   │ cacheable modules 5.74 KiB
dbgate-plugin-sqlite   │   [1m./index.js[39m[22m 118 bytes [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-sqlite   │   [1m./driver.js[39m[22m 1.96 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-sqlite   │   [1m./Dumper.js[39m[22m 1.16 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-sqlite   │   [1m../../../../node_modules/dbgate-query-splitter/lib/options.js[39m[22m 2.51 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
dbgate-plugin-sqlite   │ 
dbgate-plugin-sqlite   │ [1m[33mWARNING[39m[22m in [1mconfiguration
dbgate-plugin-sqlite   │ The [1m[31m'mode' option has not been set[39m[22m[1m, webpack will fallback to 'production' for this value.
dbgate-plugin-sqlite   │ [1m[32mSet 'mode' option to 'development' or 'production'[39m[22m[1m to enable defaults for each environment.
dbgate-plugin-sqlite   │ You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/[39m[22m
dbgate-plugin-sqlite   │ 
dbgate-plugin-sqlite   │ webpack 5.93.0 compiled with [1m[33m1 warning[39m[22m in 336 ms
dbgate-plugin-xml      │ [31m[1mInternal Error[22m[39m: dbgate-plugin-xml@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
dbgate-plugin-xml      │     at Zx.getCandidates (C:\Users\A\AppData\Local\Volta\tools\image\yarn\4.3.1\bin\yarn.js:205:8149)
dbgate-plugin-xml      │     at Pd.getCandidates (C:\Users\A\AppData\Local\Volta\tools\image\yarn\4.3.1\bin\yarn.js:141:1311)
dbgate-plugin-xml      │     at C:\Users\A\AppData\Local\Volta\tools\image\yarn\4.3.1\bin\yarn.js:210:8420
dbgate-plugin-xml      │     at Yy (C:\Users\A\AppData\Local\Volta\tools\image\yarn\4.3.1\bin\yarn.js:140:53801)
dbgate-plugin-xml      │     at ht (C:\Users\A\AppData\Local\Volta\tools\image\yarn\4.3.1\bin\yarn.js:210:8400)
dbgate-plugin-xml      │     at async Promise.allSettled (index 0)
dbgate-plugin-xml      │     at async _c (C:\Users\A\AppData\Local\Volta\tools\image\yarn\4.3.1\bin\yarn.js:140:53129)
dbgate-plugin-xml      │     at async C:\Users\A\AppData\Local\Volta\tools\image\yarn\4.3.1\bin\yarn.js:210:9166
dbgate-plugin-xml      │     at async Qi.startProgressPromise (C:\Users\A\AppData\Local\Volta\tools\image\yarn\4.3.1\bin\yarn.js:140:137362)
dbgate-plugin-xml      │     at async St.resolveEverything (C:\Users\A\AppData\Local\Volta\tools\image\yarn\4.3.1\bin\yarn.js:210:7138)
Error: spawn yarn ENOENT
    at notFoundError (S:\dev\dbgate\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (S:\dev\dbgate\node_modules\cross-spawn\lib\enoent.js:40:16)
    at cp.emit (S:\dev\dbgate\node_modules\cross-spawn\lib\enoent.js:27:25)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn yarn',
  path: 'yarn',
  spawnargs: [ 'build:frontend' ]
}
```

**Comment by AnisRouane67** [comment]
found the error: needed to run yarn workspace dbgate-plugin-xml install to fix the issue
