### ISSUE TITLE
Test connection failed (ERR_DLOPEN_FAILED)

### ISSUE THREAD

**Issue by jeffcwolf** [dbgate/dbgate#869]
I have no idea what changed, but I can no longer connect to a database I was working on (I am able to open it with other sqlite software):

Error: dlopen(/var/folders/z1/zytglzsx2ln1xv7f0sd1nl880000gn/T/.org.chromium.Chromium.aXaCpB, 0x0001): tried: '/var/folders/z1/zytglzsx2ln1xv7f0sd1nl880000gn/T/.org.chromium.Chromium.aXaCpB' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/var/folders/z1/zytglzsx2ln1xv7f0sd1nl880000gn/T/.org.chromium.Chromium.aXaCpB' (no such file), '/var/folders/z1/zytglzsx2ln1xv7f0sd1nl880000gn/T/.org.chromium.Chromium.aXaCpB' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/private/var/folders/z1/zytglzsx2ln1xv7f0sd1nl880000gn/T/.org.chromium.Chromium.aXaCpB' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/z1/zytglzsx2ln1xv7f0sd1nl880000gn/T/.org.chromium.Chromium.aXaCpB' (no such file), '/private/var/folders/z1/zytglzsx2ln1xv7f0sd1nl880000gn/T/.org.chromium.Chromium.aXaCpB' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'))
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
    at Module._extensions..node (node:internal/modules/cjs/loader:1489:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2441)
    at Module.load (node:internal/modules/cjs/loader:1214:32)
    at Module._load (node:internal/modules/cjs/loader:1030:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1242:19)
    at require (node:internal/modules/helpers:176:18)
    at bindings (/Applications/DbGate.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at new Database (/Applications/DbGate.app/Contents/Resources/app.asar/node_modules/better-sqlite3/lib/database.js:48:64)

Error JSON: {
  "code": "ERR_DLOPEN_FAILED"
}

Connection: {
  "server": "***",
  "engine": "sqlite@dbgate-plugin-sqlite",
  "databaseFile": "***",
  "connectionColor": "***"
}

Platform: darwin

I am using an older Intel-based Mac - not a newer one. Also, I wanted to install (as I was trying to determine the issue) the Intel-only version of dbgate but the download link only leads to a 404 page.

Finally, I cleared the Cache (folder in Library/Application Support) but this did not resolve the issue.

Thanks.

**Comment by janproch** [comment]
Could you please try Intel-only version?

I have fixed broken link on downloads page

https://github.com/dbgate/dbgate/releases/latest/download/dbgate-latest-x64.dmg

**Comment by gavinhewitt** [comment]
> Could you please try Intel-only version?
> 
> I have fixed broken link on downloads page
> 
> https://github.com/dbgate/dbgate/releases/latest/download/dbgate-latest-x64.dmg

I was having the same problem. This fixed it for me 🎉

**Comment by jeffcwolf** [comment]
Thank you - this worked for me.

**Comment by xxnuo** [comment]
It works.
Homebrew install dbgate on Intel Mac has this issue.
