### ISSUE TITLE
BUG: Basic auth is throwing "invalid signature" error in logs

### ISSUE THREAD

**Issue by LunarTwilight** [dbgate/dbgate#934]
**Describe the bug**
I get this error message in my logs when I go to my basic auth instance and get the username/password screen
```
{"pid":638380,"caller":"auth","errorMessage":"invalid signature","errorObject":{"name":"JsonWebTokenError","message":"invalid signature"},"errorStack":"JsonWebTokenError: invalid signature\n    at /usr/lib/node_modules/dbgate-serve/node_modules/jsonwebtoken/verify.js:133:19\n    at getSecret (/usr/lib/node_modules/dbgate-serve/node_modules/jsonwebtoken/verify.js:90:14)\n    at module.exports [as verify] (/usr/lib/node_modules/dbgate-serve/node_modules/jsonwebtoken/verify.js:94:10)\n    at authMiddleware (/usr/lib/node_modules/dbgate-serve/node_modules/dbgate-api/src/controllers/auth.js:67:25)\n    at Layer.handle [as handle_request] (/usr/lib/node_modules/dbgate-serve/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/lib/node_modules/dbgate-serve/node_modules/express/lib/router/index.js:328:13)\n    at /usr/lib/node_modules/dbgate-serve/node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/usr/lib/node_modules/dbgate-serve/node_modules/express/lib/router/index.js:346:12)\n    at next (/usr/lib/node_modules/dbgate-serve/node_modules/express/lib/router/index.js:280:10)\n    at serveStatic (/usr/li... (truncated)","level":50,"msg":"Sending invalid token error","time":1730841962699}
```

**To Reproduce**
1. Go to DbGate
3. See error in logs

**Expected behavior**
No error

**Version Information (please complete the following information):**
 - OS: Ubuntu
 - App Version: 5.5.6
 - Install source: NPM
 - Type: web
 - Database engine: sqlite & redis

**Comment by LunarTwilight** [comment]
This seems to prevent dbgate from working, I'm stuck on the loading screen with this in my logs.

**Comment by janproch** [comment]
I tested it now, it worked. Only I added configuration check

You should have BASIC_AUTH, LOGIN, PASSWORD env variables set

Variables OAUTH_xxx should be unset

**Comment by LunarTwilight** [comment]
Yeah it's working for me now, not sure why it wasn't loading then.

I have LOGINS, LOGIN_PASSWORD_admin, and LOGIN_PERMISSIONS_admin set, no other auth vars
