### ISSUE TITLE
BUG: Latest beta fails to run

### ISSUE THREAD

**Issue by rubenelshof** [dbgate/dbgate#946]
**Describe the bug**
I get the following error when trying to launch the latest beta Docker image.
```
{"pid":1,"caller":"directories","level":30,"msg":"Creating directory /root/.dbgate/logs","time":1732631535465}
{"pid":1,"caller":"apiIndex","name":"main","level":30,"msg":"Starting API process version 5.5.7-beta.61","time":1732631535469}
{"pid":1,"caller":"apiIndex","name":"main","errorMessage":"Cannot find module 'axios'\nRequire stack:\n- /home/dbgate-docker/bundle.js","errorObject":{"code":"MODULE_NOT_FOUND","requireStack":["/home/dbgate-docker/bundle.js"]},"errorStack":"Error: Cannot find module 'axios'\nRequire stack:\n- /home/dbgate-docker/bundle.js\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)\n    at Module._load (node:internal/modules/cjs/loader:981:27)\n    at Module.require (node:internal/modules/cjs/loader:1231:19)\n    at require (node:internal/modules/helpers:177:18)\n    at 58938 (/home/dbgate-docker/bundle.js:2:1555115)\n    at __webpack_require__ (/home/dbgate-docker/bundle.js:2:1978695)\n    at 24749 (/home/dbgate-docker/bundle.js:2:1176201)\n    at __webpack_require__ (/home/dbgate-docker/bundle.js:2:1978695)\n    at 94253 (/home/dbgate-docker/bundle.js:2:1313709)\n    at __webpack_require__ (/home/dbgate-docker/bundle.js:2:1978695)","level":60,"msg":"Uncaught exception, exiting process","time":1732631535483}
```
After this error the container exits.

**To Reproduce**
Run `docker run -it -p 8199:3000 dbgate/dbgate:beta-alpine`

**Expected behavior**
For dbgate to run.

**Version Information (please complete the following information):**
 - OS: Debian
 - Install source: Docker
 - Type - Web

**Comment by janproch** [comment]
Good catch, thanks, I replicated it and I am going to solve this

**Comment by janproch** [comment]
Docker-Beta is fixed now

There are still smaller UX problems in docker-beta, will be solved tomorrow

Premium-docker-beta is still broken

**Comment by janproch** [comment]
Fixed
