### ISSUE TITLE
BUG: connection got wrong server ip

### ISSUE THREAD

**Issue by fenggeHu** [dbgate/dbgate#958]
I used dbgate on windows10, it's good. Now i use dbgate on mac12, Server: localhost or 127.0.0.1
both I got Connect failed:  Access denied for user 'root'@'172.18.0.1' (using password: YES)

why?
---------------------------------
Show Detail: 
 
Not connected
default
No new updates
General
SSH Tunnel
SSL
Advanced
Connection type

MySQL
Connection mode

Host and port
Server
127.0.0.1
Port
3306
User
root
Password
123456
Password mode

Save raw (UNSAFE!!)
 
Default database
hfdx
 
Display name
hfdx
Color
Connect failed:  Access denied for user 'root'@'172.18.0.1' (using password: YES) Show detail

Database connection error
Error: Access denied for user 'root'@'172.18.0.1' (using password: YES)
    at Packet.asError (/Applications/DbGate.app/Contents/Resources/app.asar/node_modules/mysql2/lib/packets/packet.js:740:17)
    at ClientHandshake.execute (/Applications/DbGate.app/Contents/Resources/app.asar/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/Applications/DbGate.app/Contents/Resources/app.asar/node_modules/mysql2/lib/base/connection.js:475:34)
    at PacketParser.onPacket (/Applications/DbGate.app/Contents/Resources/app.asar/node_modules/mysql2/lib/base/connection.js:93:12)
    at PacketParser.executeStart (/Applications/DbGate.app/Contents/Resources/app.asar/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Applications/DbGate.app/Contents/Resources/app.asar/node_modules/mysql2/lib/base/connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)

Error JSON: {
  "code": "ER_ACCESS_DENIED_ERROR",
  "errno": 1045,
  "sqlState": "28000",
  "sqlMessage": "Access denied for user 'root'@'172.18.0.1' (using password: YES)"
}

Connection: {
  "server": "***",
  "engine": "mysql@dbgate-plugin-mysql",
  "user": "***",
  "password": "***",
  "passwordMode": "saveRaw",
  "defaultDatabase": "***",
  "displayName": "***",
  "_id": "***",
  "unsaved": false,
  "authType": "hostPort"
}

Platform: darwin

**Comment by jamespandaz** [comment]
Are you running the DB in a docker container? If so, then dbgate is working correctly. I believe it's Docker is resolving localhost as whatever the container IP (in your case 172.18.0.1). 

It looks like it's an authentication issue and you should double check your login information or the DB user setup :)

**Comment by janproch** [comment]
Should be fixed in 6.1.3

Try to adjust Local host address for SSH connections in Connection settings

![Image](https://github.com/user-attachments/assets/2c5aab42-14b9-4b67-a628-12f5511c874d)
